name: Notification on push

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    types: [opened, closed, reopened, synchronized]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master